### ISSUE TITLE
Github Actions: Draft Paper run

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#48] opened 2023-04-13 06:48 UTC
Currently we are planning to publish a software paper at the Journal of Open Source Software (https://joss.theoj.org/). I briefly request the "how to publish"section to be reviewed by the assignee.

Currently, we have made a draft for the paper in a markdown format. A github action (https://github.com/openjournals/joss-papers/actions/workflows/draft-paper.yml) is supposed to convert the markdown into a pdf in the prescribed format for the journal. However, the GH action is giving an error.

I perceive this to be a lower-hanging fruit; that perhaps takes less effort but also has a big impact in getting our draft near completion. I request the assignee to check it out in a new github branch.

Couple possible errors: 
- some encoding in the github action file (https://github.com/mn5hk/pyshbundle/blob/main/.github/workflows/draft-pdf.yml ; currently pointed to a different md file named paper_joss.md);
- some error in equations being generated in the markdown file, causing GH action to fail

Also check issue #38

**Comment by abhimhamane** [comment] 2023-04-13 09:16
Thank you @mn5hk, for assigning this task and showing trust in me. I'll look into the points made in issue #38 and try to solve the problem ASAP. I've already forked the repo; I'll create a new branch to avoid corrupting the main branch.

**Comment by abhimhamane** [comment] 2023-04-13 12:14
I guess I solved the `build draft PDF` issue, here is the explaination.

The following image shows the LaTeX file before the changes were made:
![Screenshot from 2023-04-13 17-10-21](https://user-images.githubusercontent.com/97011961/231748266-4b5f47c5-05b1-492d-b673-659e8ccd1c8e.png)

It can be seen that in the LaTeX code the `\begin{equation}...\end{equation}` is wrapped in another tag `\[ .. \]`, both of them are to initiate the `math mode`. The [Errors while processing latex files - Florida State Uni](https://web1.eng.famu.fsu.edu/~dommelen/l2h/errors.html#badmathe) states that `Bad math environment delimiter` can occur when one is entering `math-mode` while already in `math-mode`. This is mostly due the preview settings of markdown, in order to viz `LaTeX` equations we need `$$ ... $$` in markdown, but `Pandocs` interprets it as entering `math-mode` indicated by `\[ .. \]`.
![Screenshot from 2023-04-13 17-15-37](https://user-images.githubusercontent.com/97011961/231749546-ddeed7cf-69d6-45c7-a233-f3b621425322.png)

Another [stack-overflow thread](https://tex.stackexchange.com/questions/40492/what-are-the-differences-between-align-equation-and-displaymath/40531#40531) explained the different `math-mode` 

I tried by removing the `$$ .. $$` and I guess it solved the pdf building issue. But now I'm getting issue with upload step.
![Screenshot from 2023-04-13 17-32-51](https://user-images.githubusercontent.com/97011961/231752679-923fb4e4-7d09-459b-9b0f-b8a9ecaf4c05.png)

Can you tell me what could be the cause for upload error.

Regards,
Abhishek

**Comment by abhimhamane** [comment] 2023-04-13 14:37
Hi @mn5hk ,

I think I solved the math markdown error and now its generating pdf too. I changed the `.yml. file a bit.

![Screenshot from 2023-04-13 20-03-25](https://user-images.githubusercontent.com/97011961/231793463-b0f47dd9-c6e1-4b15-b1a4-ef9347c7d2c7.png)

![Screenshot from 2023-04-13 19-47-24](https://user-images.githubusercontent.com/97011961/231788200-d5820cea-ccb1-4f36-ab90-caa2b7cdbb61.png)


Here is the link to generated pdf file - [paper.pdf](https://github.com/mn5hk/pyshbundle/files/11223146/paper.pdf)

I found some minor typos in the equations and citations, I have fixed those as well. But somehow there is still the issue with table and image placement.

Regards,
Abhishek

**Comment by mn5hk** [comment] 2023-04-13 14:50
@abhimhamane This looks much better. The table we can rearrange later, if required. Pictures we need to figure out a way to fix.

I will start you assigning for documentation works soon.

Best,
AS

**Comment by mn5hk** [comment] 2023-04-13 19:03
@abhimhamane could you merge this progress to the main branch?

Thanks,
Amin

**Comment by abhimhamane** [comment] 2023-04-13 19:21
Hi @mn5hk ,

Can you look at the updated pdf - [paper.pdf](https://github.com/mn5hk/pyshbundle/files/11225702/paper.pdf), I think I've solved the table and code workflow image alignment. 

For table I have followed the [Pandoc user guide for tables](https://pandoc.org/MANUAL.html#tables) and changed the table markdown format.
![Screenshot from 2023-04-14 00-45-49](https://user-images.githubusercontent.com/97011961/231860733-c4f964bb-f5fd-4b99-94bd-df7c1f35f3f1.png)

The drawback of my changes is that the markdown preview sometimes does not show the changes appropriately.

After this review, I'll be happy merge the progress.

Regards,
Abhishek

**Comment by mn5hk** [comment] 2023-04-13 19:28
Hi @abhimhamane , well done. Please go forward with the merge.

Tomorrow I will create a new issue regarding documentations. Additionally, feel free to critically read through the current paper draft. Critical reviews are more than welcome at this point. We could always improve the manuscript :)

**Comment by abhimhamane** [comment] 2023-04-13 19:36
@mn5hk I have created the pull request, please check it and let me know if I need to make any more changes.

**Closed** 2023-05-08 19:22 UTC
Labels: bug
